void menu(int sales[FILAS_SALES][COLUMNAS_SALES], char vendedores[FILAS_VENDEDORES][COLUMNAS_VENDEDORES], char productos[FILAS_PRODUCTOS][COLUMNAS_PRODUCTOS], int ventasVendedores[SIZE_VENTAS_VENDEDORES], int ventasProductos[SIZE_VENTAS_PRODUCTOS]);


